language: ruby
rvm: 2.6.1

services:
  - postgresql
  - docker

before_install:
  - mv config/database.yml config/database.temp.yml
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - gem install bundler
  - bundle check || bundle install
  - bundle exec rails db:migrate RAILS_ENV=test

script:
  - bundle exec rails test

deploy:
  provider: script
  skip_cleanup: true
  script: sh $TRAVIS_BUILD_DIR/deploy.sh
  on:
    branch: master
