version: '2.1'

# ACTUAL CONFIGURATION
services:
  # DATABASE CONFIGURATION
  elasticsearch:
    container_name: bitpharma-elasticsearch
    build:
      context: config/docker/elasticsearch/
    volumes:
      - ./config/docker/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200"
      - "9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - elk

  kibana:
    container_name: bitpharma-kibana
    build:
      context: config/docker/kibana/
    volumes:
      - ./config/docker/kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - elk

  psql:
    command: postgres -c logging_collector=on
      -c log_min_duration_statement=0
      -c log_directory='/var/log/postgresql'
      -c log_min_messages='WARNING'
      -c log_rotation_age='1d'
      -c log_rotation_size='1GB'
    container_name: bitpharma-psql
    hostname: psql
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 'qusUt1i9obru4ISTUG2f'
    ports:
      - "5432"
    volumes:
      - psql:/var/log/postgresql
    networks:
      - api
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10

  rails:
    restart: always
    container_name: bitpharma-api
    build: .
    command: bin/start_rails_docker
    volumes:
      - .:/bitpharma-api
    environment:
      - DB_HOST=psql
      - DB_PASSWORD=qusUt1i9obru4ISTUG2f
      - DB_USER=postgres
      - ELASTICSEACRH_URL=http://elasticsearch:9200
      - PORT=3002
    ports:
      - "3002"
    networks:
      - api
      - elk
    depends_on:
      elasticsearch:
        condition: service_healthy
      psql:
        condition: service_healthy

networks:
  api:
    driver: bridge
  elk:
    driver: bridge

volumes:
  psql:
    driver: local